### ISSUE TITLE
Unable to install 0.3.3 via Magisk 27 to use MMRL 2.16.13

### ISSUE THREAD

**Issue by CSnowRules** [DerGoogler/MMRL-CLI#2]
0.3.3 fails to install via Magisk. My workaround was to install 0.2.3 first on Magisk then update to 0.3.3 via MMRL.

**Comment by DerGoogler** [comment]
Could you please provide logs

**Comment by Fr4ncky** [comment]
i believe i have the same problem.. here is the log!
[magisk_install_log_2024-06-03T04.29.58.log](https://github.com/user-attachments/files/15530284/magisk_install_log_2024-06-03T04.29.58.log)

**Comment by DerGoogler** [comment]
That's a problem with line endings. Linux has LF but the scripts have CRLF

**Comment by devnoname120** [comment]
Here is a fixed version done by calling `dos2unix` on all the textual files.
[mmrl-0.3.3-module-aarch64_fixed.zip](https://github.com/user-attachments/files/15749671/mmrl-0.3.3-module-aarch64_fixed.zip)
